@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModuLightParser" as ModuLightParser LOGIC_COLOR
participant ":CompStatsCommandParser" as CompStatsCommandParser LOGIC_COLOR
participant "a:CompStatsCommand" as CompStatsCommand LOGIC_COLOR
participant ":StatsCalculator" as StatsCalculator LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(compStats c/Midterm)
activate LogicManager

LogicManager -> ModuLightParser : parseCommand(compStats c/Midterm)
activate ModuLightParser

create CompStatsCommandParser
ModuLightParser -> CompStatsCommandParser :CompStatsCommandParser()
activate CompStatsCommandParser

CompStatsCommandParser --> ModuLightParser
deactivate CompStatsCommandParser

ModuLightParser -> CompStatsCommandParser : parse(" c/Midterm")
activate CompStatsCommandParser

create CompStatsCommand
CompStatsCommandParser -> CompStatsCommand
activate CompStatsCommand

CompStatsCommand --> CompStatsCommandParser : c
deactivate CompStatsCommand

CompStatsCommandParser --> ModuLightParser : c
deactivate CompStatsCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CompStatsCommandParser -[hidden]-> ModuLightParser
destroy CompStatsCommandParser

ModuLightParser --> LogicManager : c
deactivate ModuLightParser

LogicManager -> CompStatsCommand : execute()
activate CompStatsCommand

CompStatsCommand -> Model : getStudentList()
activate Model

Model --> CompStatsCommand
deactivate Model

create StatsCalculator
CompStatsCommand ->StatsCalculator : generateOverallStatsSummary(List<Student> students)
activate StatsCalculator


StatsCalculator --> CompStatsCommand
deactivate StatsCalculator
StatsCalculator -[hidden]-> CompStatsCommand
destroy StatsCalculator

CompStatsCommand --> LogicManager : result
deactivate CompStatsCommand
CompStatsCommand -[hidden]-> LogicManager : result
destroy CompStatsCommand

[<--LogicManager
deactivate LogicManager
@enduml
