@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nModel" as Model
Class "<<interface>>\nReadOnlySscBook" as ReadOnlySscBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class SscBook
Class ModelManager
Class UserPrefs

Class UniqueSscList
Class Ssc

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

SscBook .up.|> ReadOnlySscBook

ModelManager .up.|> Model
Model .left.> ReadOnlyUserPrefs
Model .right.> ReadOnlySscBook
ModelManager -right-> "1" SscBook
ModelManager -left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

SscBook *--> "1" UniqueSscList
UniqueSscList --> "~* all" Ssc

Ssc -[hidden]up--> I


note right of SscBook: SscBook = StudentBook,\nStudentScoreBook\n and GradedComponentBook
note right of Ssc: Ssc = Student,\nStudentScore\n and GradedComponent
note right of ReadOnlySscBook: ReadOnlySscBook = ReadOnlyStudentBook,\nReadOnlyStudentScoreBook\n and ReadOnlyGradedComponentBook
note right of UniqueSscList: UniqueSscList = UniqueStudentList,\nUniqueStudentScoreList\n and UniqueGradedComponentList


ModelManager --> "~* filtered" Ssc
@enduml
