@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModuLightParser" as ModuLightParser LOGIC_COLOR
participant ":SortStudentScoreCommandParser" as SortStudentScoreCommandParser LOGIC_COLOR
participant "a:SortStudentScoreCommand" as SortStudentScoreCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(sortScore c/Midterm)
activate LogicManager

LogicManager -> ModuLightParser : parseCommand(sortScore c/Midterm)
activate ModuLightParser

create SortStudentScoreCommandParser
ModuLightParser -> SortStudentScoreCommandParser :SortStudentScoreCommandParser()
activate SortStudentScoreCommandParser

SortStudentScoreCommandParser --> ModuLightParser
deactivate SortStudentScoreCommandParser

ModuLightParser -> SortStudentScoreCommandParser : parse(" c/Midterm")
activate SortStudentScoreCommandParser

create SortStudentScoreCommand
SortStudentScoreCommandParser -> SortStudentScoreCommand
activate SortStudentScoreCommand

SortStudentScoreCommand --> SortStudentScoreCommandParser : s
deactivate SortStudentScoreCommand

SortStudentScoreCommandParser --> ModuLightParser : s
deactivate SortStudentScoreCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SortStudentScoreCommandParser -[hidden]-> ModuLightParser
destroy SortStudentScoreCommandParser

ModuLightParser --> LogicManager : s
deactivate ModuLightParser

LogicManager -> SortStudentScoreCommand : execute()
activate SortStudentScoreCommand

SortStudentScoreCommand -> Model : hasGc(GcName gcName)
activate Model

Model --> SortStudentScoreCommand
deactivate Model

SortStudentScoreCommand -> Model : sortStudentScore(GcName gcName, Boolean isReverse)
activate Model


Model --> SortStudentScoreCommand
deactivate Model

SortStudentScoreCommand --> LogicManager : result
deactivate SortStudentScoreCommand
SortStudentScoreCommand -[hidden]-> LogicManager : result
destroy SortStudentScoreCommand

[<--LogicManager
deactivate LogicManager
@enduml
