@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes sortScore command;
if () then ([given graded component exists])
  :student scores filtered and sorted;
  :students sorted accordingly;
  :Updated students and student scores list saved to ModuLight;
else ([else])
    :a error message shows up;
    :user retypes the command;
endif

: execution completed;

stop

@enduml
