@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{

Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

Class "<<interface>>\nStudentBookStorage" as StudentBookStorage

Class "<<interface>>\nStudentScoreBookStorage" as StudentScoreBookStorage

Class "<<interface>>\nGradedComponentBookStorage" as GradedComponentBookStorage

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -down-> "1" UserPrefsStorage
StorageManager -down-> "1" StudentBookStorage
StorageManager -down-> "1" StudentScoreBookStorage
StorageManager -down-> "1" GradedComponentBookStorage

Storage -down-|> UserPrefsStorage
Storage -down-|> StudentBookStorage
Storage -down-|> StudentScoreBookStorage
Storage -down-|> GradedComponentBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage

@enduml
