@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModuLightParser" as ModuLightParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedSscBook" as VersionedSscBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ModuLightParser : parseCommand(undo)
activate ModuLightParser

create UndoCommand
ModuLightParser -> UndoCommand
activate UndoCommand

UndoCommand --> ModuLightParser
deactivate UndoCommand

ModuLightParser --> LogicManager : u
deactivate ModuLightParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoSscBook()
activate Model

Model -> VersionedSscBook : undo()
activate VersionedSscBook

VersionedSscBook -> VersionedSscBook :resetData(ReadOnlySscBook)
VersionedSscBook --> Model :
deactivate VersionedSscBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
